### ISSUE TITLE
Program crashes after Converting New Default Plus

### ISSUE THREAD

**Issue by OhaDerErste** [supsm/MCPPPP#24]
![image](https://user-images.githubusercontent.com/77100649/164888400-7ee86596-b591-438d-9c05-cb32dc25b083.png)
This is the only error I get

**Comment by OhaDerErste** [comment]
![image](https://user-images.githubusercontent.com/77100649/164888459-316392d1-b84e-44e1-b1ab-3db8532f6eaf.png)
Java version doesnt even launch
My Specs:
![image](https://user-images.githubusercontent.com/77100649/164888484-1094a5b4-af89-4e19-8502-89ba7dc320e8.png)

**Comment by supsm** [comment]
It might not run because it was built on Ubuntu. Maybe you can try building from source? There also is an [unofficial aur](https://aur.archlinux.org/packages/mcpppp) if it's more convenient (slightly outdated though). Build instructions should be on the readme, let me know if there is more I need to clarify

**Comment by OhaDerErste** [comment]
thanks!
