### ISSUE TITLE
GUI: Unnecessicary functions prevent use on 10 pre-1703 and 8/7

### ISSUE THREAD

**Issue by K4sum1** [supsm/MCPPPP#31]
**Describe the bug**
The program wants GetDpiForSystem, SetProcessDpiAwarenessContext, and SetThreadDpiAwarenessContext, which are kinda useless, especially for a small program like this.

**Important stuff**
- OS: Windows
- Version/Commit Number: 0.7.4

**Comment by supsm** [comment]
It is for high-dpi screens where text may appear blurred or too small as a result of scaling. Not many people use windows pre-1703 regardless, so I feel this is a worthwhile tradeoff to make. The cli version should still work, and additionally, the web converter will work with an up-to-date browser. (mac osx <12 is also unsupported due to compiler limitations)

**Comment by K4sum1** [comment]
I decided to just use the output to see what happened, and I get no custom item textures and there's no skybox.
![2023-01-05_20 32 29](https://user-images.githubusercontent.com/77039240/210918165-cf9b8067-2e47-4ac7-916e-d9b6841de58b.png)

**Comment by supsm** [comment]
Can you send the converted pack so I can take a look? Also, it might be more convenient for support to go in the discord

**Comment by K4sum1** [comment]
Does MCPPPP need the .jar file installed in the game, or is everything not supposed to be in a MCPPPP folder?

I think I deleted the MCPPPP conversion, I can make another, or you could just run Soartex Fanver though it yourself.
